# Generated by Django 3.1.7 on 2021-04-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tags_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_1',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('tag_zone', models.IntegerField()),
                ('x_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_pos', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_table',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AddField(
            model_name='tag_1',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tag_table'),
        ),
    ]
