# Generated by Django 3.1.7 on 2021-04-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210420_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_3',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('tag_zone', models.IntegerField()),
                ('x_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tag_table')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_2',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('tag_zone', models.IntegerField()),
                ('x_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tag_table')),
            ],
        ),
    ]
