# Generated by Django 3.1.7 on 2021-04-22 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_tag_2_tag_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='tag_2',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='tag_3',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='tag_table',
            name='serial_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag_table',
            name='tag_zone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag_table',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 12, 41, 52, 322545), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag_table',
            name='x_pos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag_table',
            name='y_pos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag_table',
            name='z_pos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag_table',
            name='tag_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Tag_1',
        ),
        migrations.DeleteModel(
            name='Tag_2',
        ),
        migrations.DeleteModel(
            name='Tag_3',
        ),
    ]
