# Generated by Django 3.1.7 on 2021-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210422_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_table',
            name='z_pos',
        ),
    ]
