# Generated by Django 3.1.7 on 2021-04-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
