# Generated by Django 3.1.7 on 2021-04-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0011_delete_tag_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('serial_num', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('tag_zone', models.IntegerField()),
                ('x_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y_pos', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
